version: 2
jobs:
    build:
        working_directory: ~/flynn-game-night
        docker:
            - image: circleci/node:8-browsers
        steps:
            - checkout

            # $FIREBASE_CONFIG is a CircleCI environment variable containing the Firebase API key, etc.
            - run: echo $FIREBASE_CONFIG >> ~/flynn-game-night/src/firebase.ts

            - restore_cache:
                  key: flynn-game-night-{{ .Branch }}-{{ checksum "package.json" }}

            - run: npm install

            - save_cache:
                  key: flynn-game-night-{{ .Branch }}-{{ checksum "package.json" }}
                  paths:
                      - './node_modules'

            - run:
                  name: Angular Build
                  command: npm run build-ci

            - run:
                  name: Angular Test
                  command: npm run test-ci

            - run:
                  name: Angular Lint
                  command: npm run lint
            - run:
                  name: Deploy to Firebase
                  command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
