version: 2
jobs:
    build:
        working_directory: ~/flynn-game-night
        docker:
            - image: circleci/node:8-browsers
        steps:
            - checkout
            - restore_cache:
                  key: flynn-game-night-{{ .Branch }}-{{ checksum "package.json" }}
            - run: npm install
            - save_cache:
                  key: flynn-game-night-{{ .Branch }}-{{ checksum "package.json" }}
                  paths:
                      - './node_modules'
            - run:
                  name: angular-build
                  command: npm build-ci
            - run:
                  name: angular-test
                  command: npm test-ci
            - run:
                  name: angular-lint
                  command: npm lint
